name: CI Linux/Clang

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  clang-ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: |
          CC=clang CXX=clang++ cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build -j
      - name: Run tests
        run: |
          build/tests/FakeIt_tests
  clang-ubuntu-18-04:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: |
          CC=clang CXX=clang++ cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build -j
      - name: Run tests
        run: |
          build/tests/FakeIt_tests
