name: CI Linux/GCC

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  coverage:
    runs-on: ubuntu-20.04
    steps:
      - name: Install LCOV
        run: sudo apt install -y lcov
      - uses: actions/checkout@v2
      - name: Build project
        run: |
          CC=gcc CXX=g++ cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON
          cmake --build build -j
      - name: Run tests
        run: |
          build/tests/FakeIt_tests
      - name: Generate report
        run: |
          cd build/tests/CMakeFiles/FakeIt_tests.dir
          gcov *.o
          lcov --directory . -c -o report.info
          lcov --remove report.info '/usr/*' '*/tests/*' -o report_filtered.info
      - name: Upload report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./build/tests/CMakeFiles/FakeIt_tests.dir/report_filtered.info
  gcc-ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: |
          CC=gcc CXX=g++ cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build -j
      - name: Run tests
        run: |
          build/tests/FakeIt_tests
  gcc-ubuntu-18-04:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: |
          CC=gcc CXX=g++ cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build -j
      - name: Run tests
        run: |
          build/tests/FakeIt_tests
